services:
  # 1. LA BASE DE DATOS
  db:
    image: mariadb:10.11
    container_name: codemized_db
    restart: always
    env_file: 
      - .env
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # 2. EL BACKEND (FastAPI)
  backend:
    build: ./backend
    container_name: codemized_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - .env
    networks:
      - app_network

  # 3. EL FRONTEND (Next.js)
  frontend:
    build: ./frontend
    container_name: codemized_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

# Definimos la red explícitamente
networks:
  app_network:
    driver: bridge

# Definimos el volumen
volumes:
  db_data: